from typing import Any
from org.bukkit.block import Block
from org.bukkit.block import SculkCatalyst
from org.bukkit.event import Cancellable
from org.bukkit.event import HandlerList
from org.bukkit.event.entity import EntityDeathEvent
from typing import Optional

class SculkBloomEvent(BlockEvent, Cancellable):
    """
    Represents an event triggered when a new cursor is created by a {@link SculkCatalyst}.
    <p>
    <strong>Cursor Definition:</strong>
    A cursor in this context is a dynamic marker or pointer generated by the
    SculkCatalyst. It occupies a block and spreads sculk as it moves. It is
    similar to entity, but it is not an entity. Cursors are ticked by the
    tile entity.
    <p>
    <strong>Triggers for Cursor Creation:</strong>
    <ul>
    <li>An entity, when killed and drops experience, within an 8-block radius of a {@link SculkCatalyst}.</li>
    <li>An explicit call from a plugin using {@link SculkCatalyst#bloom(Block, int)}.</li>
    </ul>
    <p>
    The result of {@link #getBlock()} is the location that the cursor is spawning at.
    """

    handlers: HandlerList

    def __init__(self, the_block: Block, charge: int) -> None:
        """
        Initializes the SculkBloomEvent with the specified block and charge.

        :param the_block: The block associated with this event.
        :param charge: The charge of the cursor.
        """
        ...

    def get_charge(self) -> int:
        """
        Returns the charge of the cursor, &lt; 1000 by default.

        :return: the charge of the cursor
        """
        ...

    def set_charge(self, charge: int) -> None:
        """
        Sets the charge of the cursor.
        <p>
        Increasing the charge of a cursor makes the cursor last longer, giving
        it more time to spread sculk blocks across a larger range.
        <p>
        Typically, charges should be set to the exp reward of a mob
        ({@link EntityDeathEvent#getDroppedExp()}), which is usually
        3-5 for animals, and 5-10 for the average mob (up to 50 for
        wither skeletons). Roughly speaking, for each charge, 1 more
        sculk block will be placed.

        :param charge: the charge of the cursor.
        """
        ...

    def is_cancelled(self) -> bool:
        """
        Checks if the event is cancelled.

        :return: True if the event is cancelled, False otherwise.
        """
        ...

    def set_cancelled(self, cancel: bool) -> None:
        """
        Sets the cancellation state of the event.

        :param cancel: True to cancel the event, False otherwise.
        """
        ...

    @staticmethod
    def get_handlers() -> HandlerList:
        """
        Gets the handler list for this event.

        :return: the handler list for this event.
        """
        ...

    @staticmethod
    def get_handler_list() -> HandlerList:
        """
        Gets the static handler list for this event.

        :return: the static handler list for this event.
        """
        ...