from typing import Any
from org.bukkit import NamespacedKey
from org.bukkit import Keyed
from enum import Enum

class Statistic(Enum, Keyed):
    """
    Represents a countable statistic, which is tracked by the server.
    """

    DAMAGE_DEALT = ...
    DAMAGE_TAKEN = ...
    DEATHS = ...
    MOB_KILLS = ...
    PLAYER_KILLS = ...
    FISH_CAUGHT = ...
    ANIMALS_BRED = ...
    LEAVE_GAME = ...
    JUMP = ...
    DROP_COUNT = ...
    DROP = ...
    PICKUP = ...
    PLAY_ONE_MINUTE = ...
    TOTAL_WORLD_TIME = ...
    WALK_ONE_CM = ...
    WALK_ON_WATER_ONE_CM = ...
    FALL_ONE_CM = ...
    SNEAK_TIME = ...
    CLIMB_ONE_CM = ...
    FLY_ONE_CM = ...
    WALK_UNDER_WATER_ONE_CM = ...
    MINECART_ONE_CM = ...
    BOAT_ONE_CM = ...
    PIG_ONE_CM = ...
    HORSE_ONE_CM = ...
    SPRINT_ONE_CM = ...
    CROUCH_ONE_CM = ...
    AVIATE_ONE_CM = ...
    MINE_BLOCK = ...
    USE_ITEM = ...
    BREAK_ITEM = ...
    CRAFT_ITEM = ...
    KILL_ENTITY = ...
    ENTITY_KILLED_BY = ...
    TIME_SINCE_DEATH = ...
    TALKED_TO_VILLAGER = ...
    TRADED_WITH_VILLAGER = ...
    CAKE_SLICES_EATEN = ...
    CAULDRON_FILLED = ...
    CAULDRON_USED = ...
    ARMOR_CLEANED = ...
    BANNER_CLEANED = ...
    BREWINGSTAND_INTERACTION = ...
    BEACON_INTERACTION = ...
    DROPPER_INSPECTED = ...
    HOPPER_INSPECTED = ...
    DISPENSER_INSPECTED = ...
    NOTEBLOCK_PLAYED = ...
    NOTEBLOCK_TUNED = ...
    FLOWER_POTTED = ...
    TRAPPED_CHEST_TRIGGERED = ...
    ENDERCHEST_OPENED = ...
    ITEM_ENCHANTED = ...
    RECORD_PLAYED = ...
    FURNACE_INTERACTION = ...
    CRAFTING_TABLE_INTERACTION = ...
    CHEST_OPENED = ...
    SLEEP_IN_BED = ...
    SHULKER_BOX_OPENED = ...
    TIME_SINCE_REST = ...
    SWIM_ONE_CM = ...
    DAMAGE_DEALT_ABSORBED = ...
    DAMAGE_DEALT_RESISTED = ...
    DAMAGE_BLOCKED_BY_SHIELD = ...
    DAMAGE_ABSORBED = ...
    DAMAGE_RESISTED = ...
    CLEAN_SHULKER_BOX = ...
    OPEN_BARREL = ...
    INTERACT_WITH_BLAST_FURNACE = ...
    INTERACT_WITH_SMOKER = ...
    INTERACT_WITH_LECTERN = ...
    INTERACT_WITH_CAMPFIRE = ...
    INTERACT_WITH_CARTOGRAPHY_TABLE = ...
    INTERACT_WITH_LOOM = ...
    INTERACT_WITH_STONECUTTER = ...
    BELL_RING = ...
    RAID_TRIGGER = ...
    RAID_WIN = ...
    INTERACT_WITH_ANVIL = ...
    INTERACT_WITH_GRINDSTONE = ...
    TARGET_HIT = ...
    INTERACT_WITH_SMITHING_TABLE = ...
    STRIDER_ONE_CM = ...

    type: Any = ...
    key: NamespacedKey = ...

    def getType(self) -> "Type":
        """
        Gets the type of this statistic.
        """
        pass

    def isSubstatistic(self) -> bool:
        """
        Checks if this is a substatistic.
        """
        pass

    def isBlock(self) -> bool:
        """
        Checks if this is a substatistic dealing with blocks.
        """
        pass

    def getKey(self) -> NamespacedKey:
        pass

    class Type(Enum):
        """
        The type of statistic.
        """

        UNTYPED = ...
        ITEM = ...
        BLOCK = ...
        ENTITY = ...
