from enum import Enum

class TreeType(Enum):
    """
    Tree and organic structure types.
    """
    TREE = ...
    """Regular tree, no branches"""

    BIG_TREE = ...
    """Regular tree, extra tall with branches"""

    REDWOOD = ...
    """Redwood tree, shaped like a pine tree"""

    TALL_REDWOOD = ...
    """Tall redwood tree with just a few leaves at the top"""

    BIRCH = ...
    """Birch tree"""

    JUNGLE = ...
    """Standard jungle tree; 4 blocks wide and tall"""

    SMALL_JUNGLE = ...
    """Smaller jungle tree; 1 block wide"""

    COCOA_TREE = ...
    """Jungle tree with cocoa plants; 1 block wide"""

    JUNGLE_BUSH = ...
    """Small bush that grows in the jungle"""

    RED_MUSHROOM = ...
    """Big red mushroom; short and fat"""

    BROWN_MUSHROOM = ...
    """Big brown mushroom; tall and umbrella-like"""

    SWAMP = ...
    """Swamp tree (regular with vines on the side)"""

    ACACIA = ...
    """Acacia tree."""

    DARK_OAK = ...
    """Dark Oak tree."""

    MEGA_REDWOOD = ...
    """Mega redwood tree; 4 blocks wide and tall"""

    MEGA_PINE = ...
    """Mega pine tree"""

    TALL_BIRCH = ...
    """Tall birch tree"""

    CHORUS_PLANT = ...
    """Large plant native to The End"""

    CRIMSON_FUNGUS = ...
    """Large crimson fungus native to the nether"""

    WARPED_FUNGUS = ...
    """Large warped fungus native to the nether"""

    AZALEA = ...
    """Tree with large roots which grows above lush caves"""

    MANGROVE = ...
    """Mangrove tree"""

    TALL_MANGROVE = ...
    """Tall mangrove tree"""

    CHERRY = ...
    """Cherry tree"""

    PALE_OAK = ...
    """Pale oak tree"""

    PALE_OAK_CREAKING = ...
    """Pale oak tree with a creaking heart"""