from typing import Collection, Optional
from random import Random
from org.bukkit import Keyed
from org.bukkit.inventory import Inventory
from org.bukkit.inventory import ItemStack
from org.jetbrains.annotations import NotNull, Nullable

"""
LootTables are technical files that represent what items should be in
naturally generated containers, what items should be dropped when killing a
mob, or what items can be fished.
<br>
See the <a href="https://minecraft.wiki/w/Loot_table">
Minecraft Wiki</a> for more information.
"""
class LootTable(Keyed):
    
    """
    Returns a mutable list of loot generated by this LootTable.

    @param random the random instance to use to generate loot
    @param context context within to populate loot
    @return a list of ItemStacks
    """
    def populate_loot(self, random: Optional[Random], context: NotNull['LootContext']) -> Collection[ItemStack]: 
        ...

    """
    Attempt to fill an inventory with this LootTable's loot.

    @param inventory the inventory to fill
    @param random the random instance to use to generate loot
    @param context context within to populate loot
    """
    def fill_inventory(self, inventory: NotNull[Inventory], random: Optional[Random], context: NotNull['LootContext']) -> None: 
        ...