from org.bukkit import Bukkit
from org.bukkit import Keyed
from org.bukkit import NamespacedKey
from org.jetbrains.annotations import NotNull
from typing import Any

"""
This enum holds a list of all known {@link LootTable}s offered by Mojang.
This list is not guaranteed to be accurate in future versions.
<br>
See the
<a href="https://minecraft.wiki/w/Loot_table#List_of_loot_tables">
Minecraft Wiki</a> for more information on loot tables.
"""
class LootTables(Keyed):
    ABANDONED_MINESHAFT: 'LootTables'
    BURIED_TREASURE: 'LootTables'
    DESERT_PYRAMID: 'LootTables'
    END_CITY_TREASURE: 'LootTables'
    IGLOO_CHEST: 'LootTables'
    JUNGLE_TEMPLE: 'LootTables'
    JUNGLE_TEMPLE_DISPENSER: 'LootTables'
    NETHER_BRIDGE: 'LootTables'
    PILLAGER_OUTPOST: 'LootTables'
    BASTION_TREASURE: 'LootTables'
    BASTION_OTHER: 'LootTables'
    BASTION_BRIDGE: 'LootTables'
    BASTION_HOGLIN_STABLE: 'LootTables'
    ANCIENT_CITY: 'LootTables'
    ANCIENT_CITY_ICE_BOX: 'LootTables'
    RUINED_PORTAL: 'LootTables'
    TRIAL_CHAMBERS_REWARD: 'LootTables'
    TRIAL_CHAMBERS_REWARD_COMMON: 'LootTables'
    TRIAL_CHAMBERS_REWARD_RARE: 'LootTables'
    TRIAL_CHAMBERS_REWARD_UNIQUE: 'LootTables'
    TRIAL_CHAMBERS_REWARD_OMINOUS: 'LootTables'
    TRIAL_CHAMBERS_REWARD_OMINOUS_COMMON: 'LootTables'
    TRIAL_CHAMBERS_REWARD_OMINOUS_RARE: 'LootTables'
    TRIAL_CHAMBERS_REWARD_OMINOUS_UNIQUE: 'LootTables'
    TRIAL_CHAMBERS_SUPPLY: 'LootTables'
    TRIAL_CHAMBERS_CORRIDOR: 'LootTables'
    TRIAL_CHAMBERS_INTERSECTION: 'LootTables'
    TRIAL_CHAMBERS_INTERSECTION_BARREL: 'LootTables'
    TRIAL_CHAMBERS_ENTRANCE: 'LootTables'
    TRIAL_CHAMBERS_CORRIDOR_DISPENSER: 'LootTables'
    TRIAL_CHAMBERS_CHAMBER_DISPENSER: 'LootTables'
    TRIAL_CHAMBERS_WATER_DISPENSER: 'LootTables'
    TRIAL_CHAMBERS_CORRIDOR_POT: 'LootTables'
    EQUIPMENT_TRIAL_CHAMBER: 'LootTables'
    EQUIPMENT_TRIAL_CHAMBER_RANGED: 'LootTables'
    EQUIPMENT_TRIAL_CHAMBER_MELEE: 'LootTables'
    SHIPWRECK_MAP: 'LootTables'
    SHIPWRECK_SUPPLY: 'LootTables'
    SHIPWRECK_TREASURE: 'LootTables'
    SIMPLE_DUNGEON: 'LootTables'
    SPAWN_BONUS_CHEST: 'LootTables'
    STRONGHOLD_CORRIDOR: 'LootTables'
    STRONGHOLD_CROSSING: 'LootTables'
    STRONGHOLD_LIBRARY: 'LootTables'
    UNDERWATER_RUIN_BIG: 'LootTables'
    UNDERWATER_RUIN_SMALL: 'LootTables'
    VILLAGE_ARMORER: 'LootTables'
    VILLAGE_BUTCHER: 'LootTables'
    VILLAGE_CARTOGRAPHER: 'LootTables'
    VILLAGE_DESERT_HOUSE: 'LootTables'
    VILLAGE_FISHER: 'LootTables'
    VILLAGE_FLETCHER: 'LootTables'
    VILLAGE_MASON: 'LootTables'
    VILLAGE_PLAINS_HOUSE: 'LootTables'
    VILLAGE_SAVANNA_HOUSE: 'LootTables'
    VILLAGE_SHEPHERD: 'LootTables'
    VILLAGE_SNOWY_HOUSE: 'LootTables'
    VILLAGE_TAIGA_HOUSE: 'LootTables'
    VILLAGE_TANNERY: 'LootTables'
    VILLAGE_TEMPLE: 'LootTables'
    VILLAGE_TOOLSMITH: 'LootTables'
    VILLAGE_WEAPONSMITH: 'LootTables'
    WOODLAND_MANSION: 'LootTables'
    ARMOR_STAND: 'LootTables'
    AXOLOTL: 'LootTables'
    BAT: 'LootTables'
    BEE: 'LootTables'
    BLAZE: 'LootTables'
    CAT: 'LootTables'
    CAVE_SPIDER: 'LootTables'
    CHICKEN: 'LootTables'
    COD: 'LootTables'
    COW: 'LootTables'
    CREEPER: 'LootTables'
    DOLPHIN: 'LootTables'
    DONKEY: 'LootTables'
    DROWNED: 'LootTables'
    ELDER_GUARDIAN: 'LootTables'
    ENDER_DRAGON: 'LootTables'
    ENDERMAN: 'LootTables'
    ENDERMITE: 'LootTables'
    EVOKER: 'LootTables'
    FOX: 'LootTables'
    GHAST: 'LootTables'
    GIANT: 'LootTables'
    GLOW_SQUID: 'LootTables'
    GOAT: 'LootTables'
    GUARDIAN: 'LootTables'
    HOGLIN: 'LootTables'
    HORSE: 'LootTables'
    HUSK: 'LootTables'
    ILLUSIONER: 'LootTables'
    IRON_GOLEM: 'LootTables'
    LLAMA: 'LootTables'
    MAGMA_CUBE: 'LootTables'
    MOOSHROOM: 'LootTables'
    MULE: 'LootTables'
    OCELOT: 'LootTables'
    PANDA: 'LootTables'
    PARROT: 'LootTables'
    PHANTOM: 'LootTables'
    PIG: 'LootTables'
    PIGLIN: 'LootTables'
    PIGLIN_BRUTE: 'LootTables'
    PILLAGER: 'LootTables'
    PLAYER: 'LootTables'
    POLAR_BEAR: 'LootTables'
    PUFFERFISH: 'LootTables'
    RABBIT: 'LootTables'
    RAVAGER: 'LootTables'
    SALMON: 'LootTables'
    SHULKER: 'LootTables'
    SILVERFISH: 'LootTables'
    SKELETON: 'LootTables'
    SKELETON_HORSE: 'LootTables'
    SLIME: 'LootTables'
    SNOW_GOLEM: 'LootTables'
    SPIDER: 'LootTables'
    SQUID: 'LootTables'
    STRAY: 'LootTables'
    STRIDER: 'LootTables'
    TRADER_LLAMA: 'LootTables'
    TROPICAL_FISH: 'LootTables'
    TURTLE: 'LootTables'
    VEX: 'LootTables'
    VILLAGER: 'LootTables'
    VINDICATOR: 'LootTables'
    WANDERING_TRADER: 'LootTables'
    WITCH: 'LootTables'
    WITHER: 'LootTables'
    WITHER_SKELETON: 'LootTables'
    WOLF: 'LootTables'
    ZOGLIN: 'LootTables'
    ZOMBIE: 'LootTables'
    ZOMBIE_HORSE: 'LootTables'
    ZOMBIE_VILLAGER: 'LootTables'
    ZOMBIFIED_PIGLIN: 'LootTables'
    ARMORER_GIFT: 'LootTables'
    BUTCHER_GIFT: 'LootTables'
    CARTOGRAPHER_GIFT: 'LootTables'
    CAT_MORNING_GIFT: 'LootTables'
    CLERIC_GIFT: 'LootTables'
    FARMER_GIFT: 'LootTables'
    FISHERMAN_GIFT: 'LootTables'
    FISHING: 'LootTables'
    FISHING_FISH: 'LootTables'
    FISHING_JUNK: 'LootTables'
    FISHING_TREASURE: 'LootTables'
    FLETCHER_GIFT: 'LootTables'
    LEATHERWORKER_GIFT: 'LootTables'
    LIBRARIAN_GIFT: 'LootTables'
    MASON_GIFT: 'LootTables'
    SHEPHERD_GIFT: 'LootTables'
    TOOLSMITH_GIFT: 'LootTables'
    WEAPONSMITH_GIFT: 'LootTables'
    UNEMPLOYED_GIFT: 'LootTables'
    BABY_VILLAGER_GIFT: 'LootTables'
    SNIFFER_DIGGING: 'LootTables'
    PANDA_SNEEZE: 'LootTables'
    CHICKEN_LAY: 'LootTables'
    ARMADILLO_SHED: 'LootTables'
    PIGLIN_BARTERING: 'LootTables'
    TRIAL_CHAMBER_KEY: 'LootTables'
    TRIAL_CHAMBER_CONSUMABLES: 'LootTables'
    OMINOUS_TRIAL_CHAMBER_KEY: 'LootTables'
    OMINOUS_TRIAL_CHAMBER_CONSUMABLES: 'LootTables'
    TRIAL_CHAMBER_ITEMS_TO_DROP_WHEN_OMINOUS: 'LootTables'
    SHEARING_BOGGED: 'LootTables'
    SHEARING_MOOSHROOM: 'LootTables'
    SHEARING_MOOSHROOM_RED: 'LootTables'
    SHEARING_MOOSHROOM_BROWN: 'LootTables'
    SHEARING_SNOW_GOLEM: 'LootTables'
    SHEARING_SHEEP: 'LootTables'
    SHEARING_SHEEP_BLACK: 'LootTables'
    SHEARING_SHEEP_BLUE: 'LootTables'
    SHEARING_SHEEP_BROWN: 'LootTables'
    SHEARING_SHEEP_CYAN: 'LootTables'
    SHEARING_SHEEP_GRAY: 'LootTables'
    SHEARING_SHEEP_GREEN: 'LootTables'
    SHEARING_SHEEP_LIGHT_BLUE: 'LootTables'
    SHEARING_SHEEP_LIGHT_GRAY: 'LootTables'
    SHEARING_SHEEP_LIME: 'LootTables'
    SHEARING_SHEEP_MAGENTA: 'LootTables'
    SHEARING_SHEEP_ORANGE: 'LootTables'
    SHEARING_SHEEP_PINK: 'LootTables'
    SHEARING_SHEEP_PURPLE: 'LootTables'
    SHEARING_SHEEP_RED: 'LootTables'
    SHEARING_SHEEP_WHITE: 'LootTables'
    SHEARING_SHEEP_YELLOW: 'LootTables'
    DESERT_WELL_ARCHAEOLOGY: 'LootTables'
    DESERT_PYRAMID_ARCHAEOLOGY: 'LootTables'
    TRAIL_RUINS_ARCHAEOLOGY_COMMON: 'LootTables'
    TRAIL_RUINS_ARCHAEOLOGY_RARE: 'LootTables'
    OCEAN_RUIN_WARM_ARCHAEOLOGY: 'LootTables'
    OCEAN_RUIN_COLD_ARCHAEOLOGY: 'LootTables'
    SHEEP: 'LootTables'
    SHEEP_BLACK: 'LootTables'
    SHEEP_BLUE: 'LootTables'
    SHEEP_BROWN: 'LootTables'
    SHEEP_CYAN: 'LootTables'
    SHEEP_GRAY: 'LootTables'
    SHEEP_GREEN: 'LootTables'
    SHEEP_LIGHT_BLUE: 'LootTables'
    SHEEP_LIGHT_GRAY: 'LootTables'
    SHEEP_LIME: 'LootTables'
    SHEEP_MAGENTA: 'LootTables'
    SHEEP_ORANGE: 'LootTables'
    SHEEP_PINK: 'LootTables'
    SHEEP_PURPLE: 'LootTables'
    SHEEP_RED: 'LootTables'
    SHEEP_WHITE: 'LootTables'
    SHEEP_YELLOW: 'LootTables'

    def __init__(self: 'LootTables', location: str) -> None:
        self.location: str = location

        def getKey(self: 'LootTables') -> NamespacedKey:
        ...

    """
    Get the {@link LootTable} corresponding to this constant. This is
    equivalent to calling {@code Bukkit.getLootTable(this.getKey());}.

    @return the associated LootTable
    """
        def getLootTable(self: 'LootTables') -> Any:
        ...